version: '3.8'

services:
  classroom:
    image: altjohndev/sitio-tech:classroom-dev
    environment:
      LIVEBOOK_PASSWORD: pleasechangeme
    volumes:
      - ..:/data
      - mix:/root/.mix
      - vscode:/root/.vscode-server-insiders
    ports:
      - 8080:8080

volumes:
  mix:
    name: sitio_tech_classroom_mix

  vscode:
    name: sitio_tech_classroom_vscode
